config/routes.rb
Rails.application.routes.draw do
  resources :places

  root 'places#index'

  get "/:id" => "contents#show"

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/place.rb
# -*- coding: utf-8 -*-
require "mechanize"

class Place < ActiveRecord::Base

  validates :name, presence: true

  geocoded_by :address
  after_validation :geocode# , if: ->(obj){ obj.address.present? and obj.address_changed? }

  scope :search_with_keyword, ->(keyword) { where(["name LIKE ? OR address LIKE ?", "%#{keyword}%", "%#{keyword}%"]) }
  scope :search_with_category, ->(category) { where(["category = ?", category]) }

  paginates_per 50

  def self.search(domain = "http://www.p-shouhinken.com/", path = "fukuoka/shop/", prefecture = "福岡県福岡市")
    agent = Mechanize.new

    begin
      p domain + path

      page = agent.get(domain + path)
      table = page.search("table.list")
      table.search("tr").each do |tr|
        place = Place.new
        tds = tr.search("td")
        tds.each_with_index do |td, i|
          unless td.text.blank?
            case i
            when 0
              place.name = td.text
            when 1
              place.category = td.text
            when 2
              place.address = prefecture + td.text.sub(/〒[0-9]{3}-[0-9]{4} /, "")
            when 3
              place.tel = td.text
            when 4
              place.url = td.at("a").attr("href")
            end
          end
        end

        p place.name

        unless Place.where(["name = ? AND address = ? AND tel = ?", place.name, place.address, place.tel]).first
          place.save

          p "SAVED"
        end
      end

      if next_page = page.search("span.next").first
        path = next_page.at("a").attr("href")
        Place.search(domain, path)
      end
    rescue TimeoutError
      warn "TimeoutError"
    rescue Mechanize::ResponseCodeError => ex
      case ex.response_code
      when "404" then
        warn "404: #{ex.page.uri} does not exist"
      when "503" then
        # follows RFC2616
        if @retryuri != "#{domain}#{path}" && sec = ex.page.header["Retry-After"]
          warn "503: will retry #{ex.page.uri} in #{sec}seconds"
          @retryuri = ex.page.uri
          sleep sec.to_i
          retry
        end
      when /\A5/ then
        warn "#{ex.response_code}: internal error"
      else
        warn ex.message
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    redirect_to "contents/about"
  end

  def show
    if params[:id] && File.exist?(path = "#{Rails.root.to_s}/app/views/contents/#{params[:id]}.html.haml")
      case params[:id]
      when "index"
        @description = "" + @@description
        @keywords = @@keywords
        @title = @@title
      end
      render :file => path, :layout => true
    else
      render :text => "Page does not exists.", :status => 404
    end
  end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @categories = Array.new
    Category.all.each do |c|
      @categories << [c.name, c.name]
    end

    keywords = Array.new
    keywords << params[:category] unless params[:category].blank?
    keywords << params[:keyword] unless params[:keyword].blank?
    @keyword = keywords.join(",")

    if params[:category].blank?
      if params[:keyword].blank?
        @places = Place.page params[:page]
      else
        @places = Place.search_with_keyword(params[:keyword]).page params[:page]
      end
    else
      if params[:keyword].blank?
        @places = Place.search_with_category(params[:category]).page params[:page]
      else
        @places = Place.search_with_category(params[:category]).search_with_keyword(params[:keyword]).page params[:page]
      end
    end

    @hash = Gmaps4rails.build_markers(@places) do |place, marker|
      marker.lat place.latitude
      marker.lng place.longitude
      marker.infowindow "#{place.name}<br>(#{place.category})<br>#{place.address}"
      marker.json({title: place.name})
    end
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :category, :address, :latitude, :longitude, :tel, :url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/contents/about.html.haml
.container
  .starter-template
    %h1 このサイトについて
    %p.lead
      2015年に福岡に引っ越して、初めて福岡市プレミアム商品券を購入してみました。地理がよくわかっていなかったので、一体どこで使えるのかよくわかりませんでした。サイトで検索しても、地図表示がなかったのでマップ上で商品券の使える店舗を検索できるサービスを作ってみました。店舗検索の一助としてお役に立てれば幸いです。

    %p
      ご意見・クレーム・ご要望などありましたら、twitterで@snusまでお願いします。<br>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "福岡プレミアム商品券の使えるお店を地図で表示しています。", :name => "description"}
    %meta{:content => "福岡,プレミアム,商品券,地図,マップ,#{@keyword}", :name => "keyword"}
    %meta{:content => "", :name => "author"}
    %title 福岡市プレミアム商品券マップ
    = stylesheet_link_tag 'application', media: 'all', "data-turbolinks-track" => true
    = javascript_include_tag 'application', "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %nav.navbar.navbar-default{:role => "navigation"}
      .container
        .navbar-header
          / The mobile navbar-toggle button can be safely removed since you do not need it in a non-responsive implementation
          -# %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
          -#   %span.sr-only Toggle navigation
          -#   %span.icon-bar
          -#   %span.icon-bar
          -#   %span.icon-bar
          %div.navbar-brand{data:{no_turbolink: true}}= link_to "福岡市プレミアム商品券マップ", root_path

        / Note that the .navbar-collapse and .collapse classes have been removed from the #navbar
        #navbar
          %ul.nav.navbar-nav
            -# %li.active
            -#   %a{:href => "#"} Home
            -# %li
            -#   %a{:href => "#about"} About
            -# %li
            -#   %a{:href => "#contact"} Contact
            -# %li.dropdown
            -#   %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            -#     Dropdown
            -#     %span.caret
            -#   %ul.dropdown-menu
            -#     %li
            -#       %a{:href => "#"} Action
            -#     %li
            -#       %a{:href => "#"} Another action
            -#     %li
            -#       %a{:href => "#"} Something else here
            -#     %li.divider{:role => "separator"}
            -#     %li.dropdown-header Nav header
            -#     %li
            -#       %a{:href => "#"} Separated link
            -#     %li
            -#       %a{:href => "#"} One more separated link
          - if controller.controller_name == "places"
            = form_for Place.new, url: places_path, remote: false, html: {method: :get, class: "navbar-form navbar-left", rol: "search"} do |f|
              .form-group
                = text_field "", :keyword, value: params[:keyword], placeholder: t("views.keyword"), class: "form-control float-left"
                = f.label t("activerecord.attributes.place.category"), class: "title float-left"
                = select_tag :category, options_for_select(@categories), include_blank: true, class: "form-control float-left clear"
              = f.submit t("links.search"), class: "btn btn-default"

            %ul.nav.navbar-nav.navbar-left
              %li= paginate @places, remote: false
              
            -# %ul.nav.navbar-nav.navbar-right
            -#   %li
            -#     = link_to "About", "/about"
            -#   %li
            -#     %a{:href => "#"} Contact

    .ad
      %script{:async => "", :src => "//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"}
        / fp-map.crudoe.com responsible
      %ins.adsbygoogle{"data-ad-client" => "ca-pub-9916693973832627", "data-ad-format" => "auto", "data-ad-slot" => "6189909932", :style => "display:block"}
      :javascript
        (adsbygoogle = window.adsbygoogle || []).push({});

    = yield

    .mastfoot
      .inner
        %p
          &copy;
          = succeed " #{Date.today.year}," do
            %a{:href => "#{root_path}"} 福岡市プレミアム商品券マップ

          Data organized by
          = succeed "." do
            Crudo

          = link_to "このサイトについて", "/about"

    :javascript
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-17879447-12', 'auto');
      ga('send', 'pageview');

app/views/places/_form.html.haml
= form_for @place do |f|
  - if @place.errors.any?
    #error_explanation
      %h2= "#{pluralize(@place.errors.count, "error")} prohibited this place from being saved:"
      %ul
        - @place.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :category
    = f.text_field :category
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :latitude
    = f.text_field :latitude
  .field
    = f.label :longitude
    = f.text_field :longitude
  .field
    = f.label :tel
    = f.text_field :tel
  .field
    = f.label :url
    = f.text_field :url
  .actions
    = f.submit 'Save'

app/views/places/_map.html.haml
#map
  %script{:charset => "utf-8", :type => "text/javascript"}
    handler = Gmaps.build('Google');
    handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    markers = handler.addMarkers(#{raw @hash.to_json});
    handler.bounds.extendWith(markers);
    handler.fitMapToBounds();
    });

app/views/places/edit.html.haml
%h1 Editing place

= render 'form'

= link_to 'Show', @place
\|
= link_to 'Back', places_path

app/views/places/index.html.haml
%script{:src => "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", :type => "text/javascript"}
%script{:src => "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", :type => "text/javascript"}

= render "map"

app/views/places/index.js.haml
$('#map').html('#{escape_javascript render("map")}');

app/views/places/new.html.haml
%h1 New place

= render 'form'

= link_to 'Back', places_path

app/views/places/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @place.name
%p
  %b Category:
  = @place.category
%p
  %b Address:
  = @place.address
%p
  %b Latitude:
  = @place.latitude
%p
  %b Longitude:
  = @place.longitude
%p
  %b Tel:
  = @place.tel
%p
  %b Url:
  = @place.url

= link_to 'Edit', edit_place_path(@place)
\|
= link_to 'Back', places_path